block.settings.google_tasklist:
  type: block_settings
  label: 'Google Tasklist'
  mapping:
    username:
      type: string
      label: 'API Key'
    theme:
      type: string
      label: 'Theme'
    link_color:
      type: string
      label: 'Link Color'
    width:
      type: string
      label: 'Width'
    height:
      type: string
      label: 'Height'
    chrome:
      type: mapping
      label: 'Chrome'
      mapping:
        noheader:
          type: string
          label: 'Chrome Option'
        nofooter:
          type: string
          label: 'Chrome Option'
        noborders:
          type: string
          label: 'Chrome Option'
        noscrollbar:
          type: string
          label: 'Chrome Option'
        transparent:
          type: string
          label: 'Chrome Option'
    border_color:
      type: string
      label: 'Border Color'
    language:
      type: string
      label: 'Language'